### ISSUE TITLE
Rollback never happens

### ISSUE THREAD

**Issue by dkomchenko** [werf/nelm#131]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

2.10.7

### How to reproduce

Hi! With registry.werf.io/werf/werf:2-stable, registry.werf.io/werf/werf:2-rock-solid, registry.werf.io/werf/werf:latest and `werf converge --require-built-images --namespace $CI_PROJECT_NAMESPACE --release ${CI_PROJECT_NAME} --values=./b2-k8s-test.values.yaml --container-registry-mirror=mirror.gcr.io  --atomic=true --timeout=120 -R` my failed release doesn't rollback, (i set wrong port in readinessProbe for tests)

### Result

ci job output: `Error: release deploy: failed release "a-geoip" (namespace: "web"): execute deploy plan: error waiting for operations completion: error executing operation: track resource readiness: track deployment: waiting for resource "web/Deployment/a-geoip" readiness failed`

### Expected result

If I change werf image to registry.werf.io/werf/werf:1.2-stable, rollback is working as expected:
`helm upgrade have failed: UPGRADE FAILED: release a-geoip failed, and has been rolled back due to atomic being set: error processing rollout phase stage: error tracking resources: deploy/a-geoip track failed: context deadline exceeded`

**Comment by ilya-lesikov** [comment]
@dkomchenko That was an actual bug. Autorollback never happened since last refactoring. The [fix](https://github.com/werf/werf/commit/f1fd80d31bf1ad8ac618427460c387030a0d03e0) is in 2.16.3.

If rollback happens there should be "Executing rollback plan" in the log.
